marginal_effects.brmsfit
Display Marginal Effects of Predictors
#### Description 
Display marginal effects of one or more numeric and/or categorical predictors including two-way
interaction effects.
Usage
## S3 method for class 'brmsfit'
marginal_effects(x, effects = NULL,
conditions = NULL, int_conditions = NULL, re_formula = NA,
robust = TRUE, probs = c(0.025, 0.975), method = c("fitted",
"predict"), spaghetti = FALSE, surface = FALSE,
categorical = FALSE, ordinal = FALSE, transform = NULL,
resolution = 100, select_points = 0, too_far = 0, ...)
marginal_effects(x, ...)
## S3 method for class 'brmsMarginalEffects'
plot(x, ncol = NULL, points = FALSE,
rug = FALSE, mean = TRUE, jitter_width = 0, stype = c("contour",
"raster"), line_args = list(), cat_args = list(),
errorbar_args = list(), surface_args = list(),
spaghetti_args = list(), point_args = list(), rug_args = list(),
theme = NULL, ask = TRUE, plot = TRUE, ...)
98 marginal_effects.brmsfit
#### Arguments
x An R object usually of class brmsfit.
effects An optional character vector naming effects (main effects or interactions) for
which to compute marginal plots. Interactions are specified by a : between
variable names. If NULL (the default), plots are generated for all main effects
and two-way interactions estimated in the model. When specifying effects
manually, all two-way interactions may be plotted even if not originally modeled.
conditions An optional data.frame containing variable #### Values to condition on. Each effect
defined in effects will be plotted separately for each row of conditions. #### Values
in the cond__ column will be used as titles of the subplots. If cond__ is not
given, the row names will be used for this purpose instead. It is recommended
to only define a few rows in order to keep the plots clear. See make_conditions
for an easy way to define conditions. If NULL (the default), numeric variables
will be marginalized by using their means and factors will get their reference
level assigned.
int_conditions An optional named list whose elements are numeric vectors of #### Values of the
second variables in two-way interactions. At these #### Values, predictions are evaluated.
The names of int_conditions have to match the variable names exactly.
Additionally, the elements of the numeric vectors may be named themselves, in
which case their names appear as labels for the conditions in the plots. Instead
of vectors, functions returning vectors may be passed and are applied on the
original #### Values of the corresponding variable. If NULL (the default), predictions
are evaluated at the mean and at mean + = 􀀀 sd.
re_formula A formula containing random effects to be considered in the marginal predictions.
If NULL, include all random effects; if NA (default), include no random
effects.
robust If TRUE (the default) the median is used as the measure of central tendency. If
FALSE the mean is used instead.
probs The quantiles to be used in the computation of credible intervals (defaults to 2.5
and 97.5 percent quantiles)
method Either "fitted" or "predict". If "fitted", plot marginal predictions of the
regression curve. If "predict", plot marginal predictions of the responses.
spaghetti Logical. Indicates if predictions should be visualized via spaghetti plots. Only
applied for numeric predictors. If TRUE, it is recommended to set argument
nsamples to a relatively small #### Value (e.g. 100) in order to reduce computation
time.
surface Logical. Indicates if interactions or two-dimensional smooths should be visualized
as a surface. Defaults to FALSE. The surface type can be controlled via
argument stype of the related plotting method.
categorical Logical. Indicates if effects of categorical or ordinal models should be shown in
terms of probabilities of response categories. Defaults to FALSE.
ordinal Deprecated! Please use argument categorical. Logical. Indicates if effects in
ordinal models should be visualized as a raster with the response categories on
the y-axis. Defaults to FALSE.
marginal_effects.brmsfit 99
transform A function or a character string naming a function to be applied on the predicted
responses before summary statistics are computed. Only allowed if method = "predict".
resolution Number of support points used to generate the plots. Higher resolution leads to
smoother plots. Defaults to 100. If surface is TRUE, this implies 10000 support
points for interaction terms, so it might be necessary to reduce resolution
when only few RAM is available.
select_points Positive number. Only relevant if points or rug are set to TRUE: Actual data
points of numeric variables that are too far away from the #### Values specified in
conditions can be excluded from the plot. #### Values are scaled into the unit interval
and then points more than select_points from the #### Values in conditions
are excluded. By default, all points are used.
too_far Positive number. For surface plots only: Grid points that are too far away from
the actual data points can be excluded from the plot. too_far determines what
is too far. The grid is scaled into the unit square and then grid points more than
too_far from the predictor variables are excluded. By default, all grid points
are used. Ignored for non-surface plots.
... Further #### Arguments such as subset or nsamples passed to predict or fitted.
ncol Number of plots to display per column for each effect. If NULL (default), ncol
is computed internally based on the number of rows of conditions.
points Logical; indicating whether the original data points should be added via geom_jitter.
Default is FALSE. Note that only those data points will be added that match the
specified conditions defined in conditions. For categorical predictors, the conditions
have to match exactly. For numeric predictors, argument select_points
is used to determine, which points do match a condition.
rug Logical; indicating whether a rug representation of predictor #### Values should be
added via geom_rug. Default is FALSE. Depends on select_points in the same
way as points does.
mean Logical; only relevant for spaghetti plots. If TRUE (the default), display the mean
regression line on top of the regression lines for each sample.
jitter_width Only used if points = TRUE: Amount of horizontal jittering of the data points.
Mainly useful for ordinal models. Defaults to 0 that is no jittering.
stype Indicates how surface plots should be displayed. Either "contour" or "raster".
line_args Only used in plots of continuous predictors: A named list of #### Arguments passed
to geom_smooth.
cat_args Only used in plots of categorical predictors: A named list of #### Arguments passed
to geom_point.
errorbar_args Only used in plots of categorical predictors: A named list of #### Arguments passed
to geom_errorbar.
surface_args Only used in surface plots: A named list of #### Arguments passed to geom_contour
or geom_raster (depending on argument stype).
spaghetti_args Only used in spaghetti plots: A named list of #### Arguments passed to geom_smooth.
point_args Only used if points = TRUE: A named list of #### Arguments passed to geom_jitter.
rug_args Only used if rug = TRUE: A named list of #### Arguments passed to geom_rug.
100 marginal_effects.brmsfit
theme A theme object modifying the appearance of the plots. For some basic themes
see ggtheme and theme_default.
ask logical; indicates if the user is prompted before a new page is plotted. Only used
if plot is TRUE.
plot logical; indicates if plots should be plotted directly in the active graphic device.
Defaults to TRUE.
#### Details
When creating marginal_effects for a particular predictor (or interaction of two predictors), one
has to choose the #### Values of all other predictors to condition on. By default, the mean is used
for continuous variables and the reference category is used for factors, but you may change these
#### Values via argument conditions. This also has an implication for the points argument: In the
created plots, only those points will be shown that correspond to the factor levels actually used in
the conditioning, in order not to create the false impression of bad model fit, where it is just due
to conditioning on certain factor levels. Since we condition on rather than actually marginalizing
variables, the name marginal_effects is possibly not ideally chosen in retrospect.
NA #### Values within factors in conditions, are interpreted as if all dummy variables of this factor are
zero. This allows, for instance, to make predictions of the grand mean when using sum coding.
To fully change colors of the created plots, one has to amend both scale_colour and scale_fill.
See scale_colour_grey or scale_colour_gradient for more details.
#### Value
An object of class brmsMarginalEffects, which is a named list with one data.frame per effect containing
all information required to generate marginal effects plots. Among others, these data.frames
contain some special variables, namely estimate__ (predicted #### Values of the response), se__ (standard
error of the predicted response), lower__ and upper__ (lower and upper bounds of the uncertainty
interval of the response), as well as cond__ (used in faceting when conditions contains
multiple rows).
The corresponding plot method returns a named list of ggplot objects, which can be further customized
using the ggplot2 package.
Examples
## Not run:
fit <- brm(count ~ log_Age_c + log_Base4_c * Trt + (1 | patient),
data = epilepsy, family = poisson())
## plot all marginal effects
plot(marginal_effects(fit), ask = FALSE)
## change colours to grey scale
me <- marginal_effects(fit, "log_Base4_c:Trt")
plot(me, plot = FALSE)[[1]] +
scale_color_grey() +
scale_fill_grey()
## only plot the marginal interaction effect of 'log_Base4_c:Trt'
marginal_smooths.brmsfit 101
## for different #### Values for 'log_Age_c'
conditions <- data.frame(log_Age_c = c(-0.3, 0, 0.3))
plot(marginal_effects(fit, effects = "log_Base4_c:Trt",
conditions = conditions))
## also incorporate random effects variance over patients
## also add data points and a rug representation of predictor #### Values
plot(marginal_effects(fit, effects = "log_Base4_c:Trt",
conditions = conditions, re_formula = NULL),
points = TRUE, rug = TRUE)
## change handling of two-way interactions
int_conditions <- list(
log_Base4_c = setNames(c(-2, 1, 0), c("b", "c", "a"))
)
marginal_effects(fit, effects = "Trt:log_Base4_c",
int_conditions = int_conditions)
marginal_effects(fit, effects = "Trt:log_Base4_c",
int_conditions = list(log_Base4_c = quantile))
## fit a model to illustrate how to plot 3-way interactions
fit3way <- brm(count ~ log_Age_c * log_Base4_c * Trt, data = epilepsy)
conditions <- make_conditions(fit3way, "log_Age_c")
marginal_effects(
fit3way, "log_Base4_c:Trt", conditions = conditions
)
## only include points close to the specified #### Values of log_Age_c
me <- marginal_effects(
fit3way, "log_Base4_c:Trt", conditions = conditions,
select_points = 0.1
)
plot(me, points = TRUE)
## End(Not run)
marginal_smooths.brmsfit
Display Smooth Terms
#### Description 
Display smooth s and t2 terms of models fitted with brms.
Usage
## S3 method for class 'brmsfit'
marginal_smooths(x, smooths = NULL,
int_conditions = NULL, probs = c(0.025, 0.975), spaghetti = FALSE,
resolution = 100, too_far = 0, subset = NULL, nsamples = NULL,
102 marginal_smooths.brmsfit
...)
marginal_smooths(x, ...)
#### Arguments
x An R object usually of class brmsfit.
smooths Optional character vector of smooth terms to display. If NULL (the default) all
smooth terms are shown.
int_conditions An optional named list whose elements are numeric vectors of #### Values of the
second variables in two-way interactions. At these #### Values, predictions are evaluated.
The names of int_conditions have to match the variable names exactly.
Additionally, the elements of the numeric vectors may be named themselves, in
which case their names appear as labels for the conditions in the plots. Instead
of vectors, functions returning vectors may be passed and are applied on the
original #### Values of the corresponding variable. If NULL (the default), predictions
are evaluated at the mean and at mean + = 􀀀 sd.
probs The quantiles to be used in the computation of credible intervals (defaults to 2.5
and 97.5 percent quantiles)
spaghetti Logical. Indicates if predictions should be visualized via spaghetti plots. Only
applied for numeric predictors. If TRUE, it is recommended to set argument
nsamples to a relatively small #### Value (e.g. 100) in order to reduce computation
time.
resolution Number of support points used to generate the plots. Higher resolution leads to
smoother plots. Defaults to 100. If surface is TRUE, this implies 10000 support
points for interaction terms, so it might be necessary to reduce resolution
when only few RAM is available.
too_far Positive number. For surface plots only: Grid points that are too far away from
the actual data points can be excluded from the plot. too_far determines what
is too far. The grid is scaled into the unit square and then grid points more than
too_far from the predictor variables are excluded. By default, all grid points
are used. Ignored for non-surface plots.
subset A numeric vector specifying the posterior samples to be used. If NULL (the
default), all samples are used.
nsamples Positive integer indicating how many posterior samples should be used. If NULL
(the default) all samples are used. Ignored if subset is not NULL.
... Currently ignored.
#### Details
Two-dimensional smooth terms will be visualized using either contour or raster plots.
#### Value
For the brmsfit method, an object of class brmsMarginalEffects. See marginal_effects for
more #### Details and documentation of the related plotting function.
me 103
Examples
## Not run:
set.seed(0)
dat <- mgcv::gamSim(1, n = 200, scale = 2)
fit <- brm(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = dat)
# show all smooth terms
plot(marginal_smooths(fit), rug = TRUE, ask = FALSE)
# show only the smooth term s(x2)
plot(marginal_smooths(fit, smooths = "s(x2)"), ask = FALSE)
# fit and plot a two-dimensional smooth term
fit2 <- brm(y ~ t2(x0, x2), data = dat)
ms <- marginal_smooths(fit2)
plot(ms, stype = "contour")
plot(ms, stype = "raster")
## End(Not run)
me Predictors with Measurement Error in brms Models
#### Description 
Specify predictors with measurement error. This function is almost solely useful when called in
formulas passed to the brms package.
Usage
me(x, sdx = NULL, gr = NULL)
#### Arguments
x The variable measured with error.
sdx Known measurement error of x treated as standard deviation.
gr Optional grouping factor to specify which #### Values of x correspond to the same
#### Value of the latent variable. If NULL (the default) each observation will have its
own #### Value of the latent variable.
#### Details
For detailed documentation see help(brmsformula).
By default, latent noise-free variables are assumed to be correlated. To change that, add set_mecor(FALSE)
to your model formula object (see examples).
See Also
brmsformula, brmsformula-helpers
104 mi
Examples
## Not run:
# sample some data
N <- 100
dat <- data.frame(
y = rnorm(N), x1 = rnorm(N),
x2 = rnorm(N), sdx = abs(rnorm(N, 1))
)
# fit a simple error-in-variables model
fit1 <- brm(y ~ me(x1, sdx) + me(x2, sdx), data = dat,
save_mevars = TRUE)
summary(fit1)
# turn off modeling of correlations
bform <- bf(y ~ me(x1, sdx) + me(x2, sdx)) + set_mecor(FALSE)
fit2 <- brm(bform, data = dat, save_mevars = TRUE)
summary(fit2)
## End(Not run)
mi Predictors with Missing #### Values in brms Models
#### Description 
Predictors with Missing #### Values in brms Models
Usage
mi(x)
#### Arguments
x The variable containing missings.
#### Details
For detailed documentation see help(brmsformula).
This function is almost solely useful when called in formulas passed to the brms package.
See Also
brmsformula
mixture 105
Examples
## Not run:
data("nhanes", package = "mice")
bform <- bf(bmi | mi() ~ age * mi(chl)) +
bf(chl | mi() ~ age) + set_rescor(FALSE)
fit <- brm(bform, data = nhanes)
summary(fit)
plot(marginal_effects(fit, resp = "bmi"), ask = FALSE)
LOO(fit, newdata = na.omit(fit$data))
## End(Not run)
mixture Finite Mixture Families in brms
#### Description 
Set up a finite mixture family for use in brms.
Usage
mixture(..., flist = NULL, nmix = 1, order = NULL)
#### Arguments
... One or more objects providing a #### Description  of the response distributions to be
combined in the mixture model. These can be family functions, calls to family
functions or character strings naming the families. For #### Details of supported
families see brmsfamily.
flist Optional list of objects, which are treated in the same way as objects passed via
the ... argument.
nmix Optional numeric vector specifying the number of times each family is repeated.
If specified, it must have the same length as the number of families passed via
... and flist.
order Ordering constraint to identify mixture components. If 'mu' or TRUE, populationlevel
intercepts of the mean parameters are ordered. If 'none' or FALSE, no
ordering constraint is applied. If NULL (the default), order is set to 'mu' if all
families are the same and 'none' otherwise. Other ordering constraints may be
implemented in the future.
#### Details
Most families supported by brms can be used to form mixtures. The response variable has to be
valid for all components of the mixture family. Currently, the number of mixture components has to
be specified by the user. It is not yet possible to estimate the number of mixture components from
the data.
106 mixture
For most mixture models, you may want to specify priors on the population-level intercepts via
set_prior to improve convergence. In addition, it is sometimes necessary to set inits = 0 in the
call to brm to allow chains to initialize properly.
for more details on the specification of mixture models, see brmsformula.
#### Value
An object of class mixfamily.
Examples
## Not run:
## simulate some data
set.seed(1234)
dat <- data.frame(
y = c(rnorm(200), rnorm(100, 6)),
x = rnorm(300),
z = sample(0:1, 300, TRUE)
)
## fit a simple normal mixture model
mix <- mixture(gaussian, gaussian)
prior <- c(
prior(normal(0, 7), Intercept, dpar = mu1),
prior(normal(5, 7), Intercept, dpar = mu2)
)
fit1 <- brm(bf(y ~ x + z), dat, family = mix,
prior = prior, chains = 2)
summary(fit1)
pp_check(fit1)
## use different predictors for the components
fit2 <- brm(bf(y ~ 1, mu1 ~ x, mu2 ~ z), dat, family = mix,
prior = prior, chains = 2)
summary(fit2)
## fix the mixing proportions
fit3 <- brm(bf(y ~ x + z, theta1 = 1, theta2 = 2),
dat, family = mix, prior = prior,
inits = 0, chains = 2)
summary(fit3)
pp_check(fit3)
## predict the mixing proportions
fit4 <- brm(bf(y ~ x + z, theta2 ~ x),
dat, family = mix, prior = prior,
inits = 0, chains = 2)
summary(fit4)
pp_check(fit4)
## compare model fit
LOO(fit1, fit2, fit3, fit4)
mm 107
## End(Not run)
mm Set up multi-membership grouping terms in brms
#### Description 
Function to set up a multi-membership grouping term in brms. The function does not evaluate its
#### Arguments – it exists purely to help set up a model with grouping terms.
Usage
mm(..., weights = NULL, scale = TRUE, dist = "gaussian")
#### Arguments
... One or more terms containing grouping factors.
weights A matrix specifying the weights of each member. It should have as many
columns as grouping terms specified in .... If NULL (the default), equally
weights are used.
scale Logical; if TRUE (the default), weights are standardized in order to sum to one
per row. If negative weights are specified, scale needs to be set to FALSE.
dist Name of the distribution of the group-level effects. Currently "gaussian" is the
only option.
See Also
brmsformula, mmc
Examples
## Not run:
# simulate some data
dat <- data.frame(
y = rnorm(100), x1 = rnorm(100), x2 = rnorm(100),
g1 = sample(1:10, 100, TRUE), g2 = sample(1:10, 100, TRUE)
)
# multi-membership model with two members per group and equal weights
fit1 <- brm(y ~ x1 + (1|mm(g1, g2)), data = dat)
summary(fit1)
# weight the first member two times for than the second member
dat$w1 <- rep(2, 100)
dat$w2 <- rep(1, 100)
fit2 <- brm(y ~ x1 + (1|mm(g1, g2, weights = cbind(w1, w2))), data = dat)
108 mmc
summary(fit2)
# multi-membership model with level specific covariate #### Values
dat$xc <- (dat$x1 + dat$x2) / 2
fit3 <- brm(y ~ xc + (1 + mmc(x1, x2) | mm(g1, g2)), data = dat)
summary(fit3)
## End(Not run)
