Package ‘brms’
October 23, 2018
Encoding UTF-8
Type Package
Title Bayesian Regression Models using 'Stan'
Version 2.6.0
Date 2018-10-22
Depends R (>= 3.2.0), Rcpp (>= 0.12.0), ggplot2 (>= 2.0.0), methods
Imports rstan (>= 2.17.2), loo (>= 2.0.0), Matrix (>= 1.1.1), mgcv (>=
1.8-13), rstantools (>= 1.3.0), bayesplot (>= 1.5.0), shinystan
(>= 2.4.0), bridgesampling (>= 0.3-0), matrixStats, nleqslv,
nlme, coda, abind, stats, utils, parallel, grDevices, backports
Suggests testthat (>= 0.9.1), RWiener, future, mice, spdep, mnormt,
lme4, MCMCglmm, ape, arm, statmod, digest, R.rsp, knitr,
rmarkdown
Description Fit Bayesian generalized (non-)linear multivariate multilevel models
using 'Stan' for full Bayesian inference. A wide range of distributions
and link functions are supported, allowing users to fit -- among others --
linear, robust linear, count data, survival, response times, ordinal,
zero-inflated, hurdle, and even self-defined mixture models all in a
multilevel context. Further modeling options include non-linear and
smooth terms, auto-correlation structures, censored data, meta-analytic
standard errors, and quite a few more. In addition, all parameters of the
response distribution can be predicted in order to perform distributional
regression. Prior specifications are flexible and explicitly encourage
users to apply prior distributions that actually reflect their beliefs.
Model fit can easily be assessed and compared with posterior predictive
checks and leave-one-out cross-validation. References: Bürkner (2017)
<doi:10.18637/jss.v080.i01>; Carpenter et al. (2017) <doi:10.18637/jss.v076.i01>.
LazyData true
NeedsCompilation no
License GPL (>= 3)
URL https://github.com/paul-buerkner/brms,
http://discourse.mc-stan.org
1
2 R topics documented:
BugReports https://github.com/paul-buerkner/brms/issues
VignetteBuilder knitr, R.rsp
RoxygenNote 6.1.0
Author Paul-Christian Bürkner [aut, cre]
Maintainer Paul-Christian Bürkner <paul.buerkner@gmail.com>
Repository CRAN
Date/Publication 2018-10-23 10:40:08 UTC
R topics documented:
brms-package..... . . . . . 5
addition-terms..... . . . . . 6
add_ic...... . . 8
as.mcmc.brmsfit..... . . . . 9
AsymLaplace..... . . . . . 10
autocor...... . 11
bayes_factor.brmsfit..... . . 11
bayes_R2.brmsfit..... . . . 12
bridge_sampler.brmsfit..... 14
brm...... . . . 15
brmsfamily.....21
brmsfit-class.....25
brmsformula.....26
brmsformula-helpers..... . 34
brmshypothesis..... . . . . 36
brm_multiple..... . . . . . 37
coef.brmsfit.....40
combine_models..... . . . 41
compare_ic.....41
control_params.brmsfit..... 42
cor_ar...... . . 43
cor_arma...... 44
cor_arr...... . . 45
cor_brms...... 46
cor_bsts...... . 47
cor_car...... . 48
cor_fixed...... 49
cor_ma...... . 50
cor_sar...... . . 51
cs...... . . . . 52
custom_family..... . . . . 53
density_ratio..... . . . . . 55
epilepsy...... . 56
ExGaussian.....57
expose_functions.brmsfit....58
expp1...... . . 58
R topics documented: 3
extract_draws.brmsfit..... . 59
fitted.brmsfit.....60
fixef.brmsfit.....62
Frechet...... . 63
GenExtreme#### Value..... . . . 64
get_prior...... . 65
gp...... . . . . 66
gr...... . . . . 68
horseshoe...... 69
Hurdle...... . . 71
hypothesis.brmsfit..... . . . 72
inhaler...... . . 74
InvGaussian.....75
inv_logit_scaled..... . . . . 76
is.brmsfit...... 76
is.brmsfit_multiple..... . . 77
is.brmsformula..... . . . . 77
is.brmsprior.....77
is.brmsterms.....78
is.cor_brms.....78
is.mvbrmsformula..... . . . 79
is.mvbrmsterms..... . . . . 79
kfold.brmsfit.....80
kidney...... . . 82
lasso...... . . . 83
launch_shinystan.brmsfit....84
logit_scaled.....85
logm1...... . . 85
log_lik.brmsfit..... . . . . . 86
log_posterior.brmsfit..... . 87
loo.brmsfit...... 88
loo_model_weights.brmsfit.... . . . . . 90
loo_predict.brmsfit..... . . 91
loo_R2.brmsfit..... . . . . 92
make_conditions..... . . . 93
make_stancode..... . . . . 94
make_standata..... . . . . . 95
marginal_effects.brmsfit....97
marginal_smooths.brmsfit.... . . . . . 101
me...... . . . . 103
mi...... . . . . 104
mixture...... . 105
mm...... . . . 107
mmc...... . . . 108
mo...... . . . . 109
model_weights.brmsfit..... 110
MultiNormal..... . . . . . 111
MultiStudentT..... . . . . . 112
4 R topics documented:
mvbrmsformula..... . . . . 112
ngrps.brmsfit..... . . . . . 113
nsamples.brmsfit..... . . . 114
pairs.brmsfit.....114
parnames...... 115
parse_bf...... . 116
plot.brmsfit.....117
posterior_average.brmsfit....118
posterior_interval.brmsfit....120
posterior_samples.brmsfit....121
posterior_summary.brmsfit.... . . . . . 122
posterior_table..... . . . . 123
post_prob.brmsfit..... . . . 124
pp_average.brmsfit..... . . 125
pp_check.brmsfit..... . . . 127
pp_mixture.brmsfit..... . . 128
predict.brmsfit..... . . . . . 130
predictive_interval.brmsfit.... . . . . . 133
print.brmsfit.....134
print.brmsprior..... . . . . 134
prior_samples.brmsfit..... . 135
prior_summary.brmsfit..... 136
ranef.brmsfit.....137
reloo...... . . . 138
residuals.brmsfit..... . . . . 139
restructure...... 141
rows2labels.....141
s...... . . . . . 142
set_prior...... . 143
Shifted_Lognormal..... . . 148
SkewNormal..... . . . . . 149
stancode.brmsfit..... . . . . 150
standata.brmsfit..... . . . . 151
stanplot.brmsfit..... . . . . 152
stanvar...... . . 153
StudentT...... . 154
summary.brmsfit..... . . . 155
theme_black.....156
theme_default..... . . . . . 157
update.brmsfit..... . . . . . 157
update_adterms..... . . . . 158
validate_newdata..... . . . 159
VarCorr.brmsfit..... . . . . 160
vcov.brmsfit.....161
VonMises...... 162
waic.brmsfit.....162
Wiener...... . . 164
ZeroInflated.....165
brms-package 5
Index 166
brms-package Bayesian Regression Models using ’Stan’
Description
The brms package provides an interface to fit Bayesian generalized multivariate (non-)linear multilevel
models using Stan, which is a C++ package for obtaining full Bayesian inference (see
http://mc-stan.org/). The formula syntax is an extended version of the syntax applied in the
lme4 package to provide a familiar and simple interface for performing regression analyses.
#### Details
The main function of brms is brm, which uses formula syntax to specify a wide range of complex
Bayesian models (see brmsformula for #### Details). Based on the supplied formulas, data, and
additional information, it writes the Stan code on the fly via make_stancode, prepares the data via
make_standata, and fits the model using Stan.
Subsequently, a large number of post-processing methods can be applied: To get an overview on
the estimated parameters, summary or marginal_effects are perfectly suited. Detailed visual
analyses can be performed by applying the pp_check and stanplot methods, which both rely on
the bayesplot package. Model comparsions can be done via loo and waic, which make use of the
loo package as well as via bayes_factor which relies on the bridgesampling package. For a full
list of methods to apply, type methods(class = "brmsfit").
Because brms is based on Stan, a C++ compiler is required. The program Rtools (available on
https://cran.r-project.org/bin/windows/Rtools/) comes with a C++ compiler for Windows.
On Mac, you should use Xcode. For further instructions on how to get the compilers running,
see the prerequisites section at the RStan-Getting-Started page.
When comparing other packages fitting multilevel models to brms, keep in mind that the latter
needs to compile models before actually fitting them, which will require between 20 and 40 seconds
depending on your machine, operating system and overall model complexity.
Thus, fitting smaller models may be relatively slow as compilation time makes up the majority of
the whole running time. For larger / more complex models however, fitting my take several minutes
or even hours, so that the compilation time won’t make much of a difference for these models.
See vignette("brms_overview") and vignette("brms_multilevel") for a general introduction
and overview of brms. For a full list of available vignettes, type vignette(package = "brms").
References
Paul-Christian Buerkner (2017). brms: An R Package for Bayesian Multilevel Models Using Stan.
Journal of Statistical Software, 80(1), 1-28. doi:10.18637/jss.v080.i01
Paul-Christian Buerkner (in press). Advanced Bayesian Multilevel Modeling with the R Package
brms. The R Journal.
The Stan Development Team. Stan Modeling Language User’s Guide and Reference Manual.
http://mc-stan.org/users/documentation.
Stan Development Team (2018). RStan: the R interface to Stan. R package version 2.18.1. http:
//mc-stan.org
6 addition-terms
See Also
brm, brmsformula, brmsfamily, brmsfit
addition-terms Additional Response Information
Description
Provide additional information on the response variable in brms models, such as censoring, truncation,
or known measurement error.
Usage
resp_se(x, sigma = FALSE)
resp_weights(x, scale = FALSE)
resp_trials(x)
resp_cat(x)
resp_dec(x)
resp_cens(x, y2 = NULL)
resp_trunc(lb = -Inf, ub = Inf)
resp_mi(sdy = NULL)
Arguments
x A vector; usually a variable defined in the data. Allowed #### Values depend on the
function: resp_se and resp_weights require positive numeric #### Values. resp_trials
and resp_cat require positive integers. resp_dec requires 0 and 1, or alternatively
'lower' and 'upper'; resp_cens requires 'left', 'none', 'right',
and 'interval' (or equivalently -1, 0, 1, and 2) to indicate left, no, right, or
interval censoring.
sigma Logical; Indicates whether the residual standard deviation parameter sigma should
be included in addition to the known measurement error. Defaults to FALSE for
backwards compatibility, but setting it to TRUE is usually the better choice.
scale Logical; Indicates whether weights should be scaled so that the average weight
equals one. Defaults to FALSE.
y2 A vector specifying the upper bounds in interval censoring.
lb A numeric vector or single numeric #### Value specifying the lower truncation bound.
ub A numeric vector or single numeric #### Value specifying the upper truncation bound.
addition-terms 7
sdy Optional known measurement error of the response treated as standard deviation.
If specified, handles measurement error and (completely) missing #### Values
at the same time using the plausible-#### Values-technique.
#### Details
These functions are almost solely useful when called in formulas passed to the brms package.
Within formulas, the resp_ prefix may be omitted. More information is given in the ’#### Details’
section of brmsformula.
#### Value
A vector containing additional information on the response variable in an appropriate format.
See Also
brm, brmsformula
Examples
## Not run:
## Random effects meta-analysis
nstudies <- 20
true_effects <- rnorm(nstudies, 0.5, 0.2)
sei <- runif(nstudies, 0.05, 0.3)
outcomes <- rnorm(nstudies, true_effects, sei)
data1 <- data.frame(outcomes, sei)
fit1 <- brm(outcomes | se(sei, sigma = TRUE) ~ 1,
data = data1)
summary(fit1)
## Probit regression using the binomial family
n <- sample(1:10, 100, TRUE) # number of trials
success <- rbinom(100, size = n, prob = 0.4)
x <- rnorm(100)
data2 <- data.frame(n, success, x)
fit2 <- brm(success | trials(n) ~ x, data = data2,
family = binomial("probit"))
summary(fit2)
## Survival regression modeling the time between the first
## and second recurrence of an infection in kidney patients.
fit3 <- brm(time | cens(censored) ~ age * sex + disease + (1|patient),
data = kidney, family = lognormal())
summary(fit3)
## Poisson model with truncated counts
fit4 <- brm(count | trunc(ub = 104) ~ log_Base4_c * Trt_c,
data = epilepsy, family = poisson())
summary(fit4)
## End(Not run)
8 add_ic
add_ic Add information criteria and fit indices to fitted model objects
Description
Add information criteria and fit indices to fitted model objects
Usage
add_ic(x, ...)
## S3 method for class 'brmsfit'
add_ic(x, ic = "loo", model_name = NULL,
overwrite = FALSE, file = NULL, force_save = FALSE, ...)
add_ic(x, ...) <- #### Value
add_loo(x, ...)
add_waic(x, ...)
Arguments
x An R object typically of class brmsfit.
... Further arguments passed to the underlying functions computing the information
criteria or fit indices.
ic, #### Value Names of the information criteria / fit indices to compute. Currently supported
are "loo", "waic", "kfold", "R2" (R-squared), and "marglik" (log marginal
likelihood).
model_name Optional name of the model. If NULL (the default) the name is taken from the
call to x.
overwrite Logical; Indicates if already stored fit indices should be overwritten. Defaults to
FALSE.
file Either NULL or a character string. In the latter case, the fitted model object
including the newly added criterion #### Values is saved via saveRDS in a file named
after the string supplied in file. The .rds extension is added automatically. If
x was already stored in a file before, the file name will be reused automatically
(with a message) unless overwritten by file. In any case, file only applies if
new criteria were actually added via add_ic or if force_save was set to TRUE.
force_save Logical; only relevant if file is specified and ignored otherwise. If TRUE, the
fitted model object will be saved regardless of whether new criteria were added
via add_ic.
as.mcmc.brmsfit 9
#### Details
The methods add_loo and add add_waic are just convenient wrappers around add_ic.
#### Value
An object of the same class as x, but with information criteria added for later usage.
Examples
## Not run:
fit <- brm(count ~ Trt, epilepsy, poisson())
# add both LOO and WAIC at once
fit <- add_ic(fit, ic = c("loo", "waic"))
print(fit$loo)
print(fit$waic)
## End(Not run)
as.mcmc.brmsfit Extract posterior samples for use with the coda package
Description
Extract posterior samples for use with the coda package
Usage
## S3 method for class 'brmsfit'
as.mcmc(x, pars = NA, exact_match = FALSE,
combine_chains = FALSE, inc_warmup = FALSE, ...)
Arguments
x An R object typically of class brmsfit
pars Names of parameters for which posterior samples should be returned, as given
by a character vector or regular expressions. By default, all posterior samples of
all parameters are extracted.
exact_match Indicates whether parameter names should be matched exactly or treated as regular
expression. Default is FALSE.
combine_chains Indicates whether chains should be combined.
inc_warmup Indicates if the warmup samples should be included. Default is FALSE. Warmup
samples are used to tune the parameters of the sampling algorithm and should
not be analyzed.
... currently unused
10 AsymLaplace
#### Value
If combine_chains = TRUE an mcmc object is returned. If combine_chains = FALSE an mcmc.list
object is returned.
AsymLaplace The Asymmetric Laplace Distribution
Description
Density, distribution function, quantile function and random generation for the asymmetric Laplace
distribution with location mu, scale sigma and asymmetry parameter quantile.
Usage
dasym_laplace(x, mu = 0, sigma = 1, quantile = 0.5, log = FALSE)
pasym_laplace(q, mu = 0, sigma = 1, quantile = 0.5,
lower.tail = TRUE, log.p = FALSE)
qasym_laplace(p, mu = 0, sigma = 1, quantile = 0.5,
lower.tail = TRUE, log.p = FALSE)
rasym_laplace(n, mu = 0, sigma = 1, quantile = 0.5)
Arguments
x, q Vector of quantiles.
mu Vector of locations.
sigma Vector of scales.
quantile Asymmetry parameter corresponding to quantiles in quantile regression (hence
the name).
log Logical; If TRUE, #### Values are returned on the log scale.
lower.tail Logical; If TRUE (default), return P(X <= x). Else, return P(X > x) .
log.p Logical; If TRUE, #### Values are returned on the log scale.
p Vector of probabilities.
n Number of samples to draw from the distribution.
#### Details
See vignette("brms_families") for #### Details on the parameterization.
autocor 11
autocor Extract Autocorrelation Structures
Description
Extract Autocorrelation Structures
Usage
autocor(object, ...)
Arguments
object An R object.
... Further arguments passed to or from other methods.
#### Value
What exactly is returned depends on the specific method.
bayes_factor.brmsfit Bayes Factors from Marginal Likelihoods
Description
Compute Bayes factors from marginal likelihoods.
Usage
## S3 method for class 'brmsfit'
bayes_factor(x1, x2, log = FALSE, ...)
Arguments
x1 A brmsfit object
x2 Another brmsfit object based on the same responses.
log Report Bayes factors on the log-scale?
... Additional arguments passed to bridge_sampler.
12 bayes_R2.brmsfit
#### Details
Computing the marginal likelihood requires samples of all variables defined in Stan’s parameters
block to be saved. Otherwise bayes_factor cannot be computed. Thus, please set save_all_pars = TRUE
in the call to brm, if you are planning to apply bayes_factor to your models.
The computation of Bayes factors based on bridge sampling requires a lot more posterior samples
than usual. A good conservative rule of thump is perhaps 10-fold more samples (read: the default
of 4000 samples may not be enough in many cases). If not enough posterior samples are provided,
the bridge sampling algoritm tends to be unstable leading to considerably different results each time
it is run. We thus recommend running bayes_factor multiple times to check the stability of the
results.
More #### Details are provided under bridgesampling:bayes_factor.
See Also
bridge_sampler, post_prob
Examples
## Not run:
# model with the treatment effect
fit1 <- brm(
count ~ log_Age_c + log_Base4_c + Trt_c,
data = epilepsy, family = negbinomial(),
prior = prior(normal(0, 1), class = b),
save_all_pars = TRUE
)
summary(fit1)
# model without the treatment effect
fit2 <- brm(
count ~ log_Age_c + log_Base4_c,
data = epilepsy, family = negbinomial(),
prior = prior(normal(0, 1), class = b),
save_all_pars = TRUE
)
summary(fit2)
# compute the bayes factor
bayes_factor(fit1, fit2)
## End(Not run)
