inhaler Clarity of inhaler instructions
#### Description 
Ezzet and Whitehead (1991) analyze data from a two-treatment, two-period crossover trial to compare
2 inhalation devices for delivering the drug salbutamol in 286 asthma patients. Patients were
asked to rate the clarity of leaflet instructions accompanying each device, using a 4-point ordinal
scale.
Usage
inhaler
Format
A dataframe of 572 observations containing information on the following 5 variables.
subject The subject number
rating The rating of the inhaler instructions on a scale ranging from 1 to 4
treat A contrast to indicate which of the two inhaler devices was used
period A contrast to indicate the time of administration
carry A contrast to indicate possible carry over effects
InvGaussian 75
Source
Ezzet, F., & Whitehead, J. (1991). A random effects model for ordinal responses from a crossover
trial. Statistics in Medicine, 10(6), 901-907.
Examples
## Not run:
## ordinal regression with family "sratio"
fit1 <- brm(rating ~ treat + period + carry,
data = inhaler, family = sratio(),
prior = set_prior("normal(0,5)"))
summary(fit1)
plot(fit1)
## ordinal regression with family "cumulative"
## and random intercept over subjects
fit2 <- brm(rating ~ treat + period + carry + (1|subject),
data = inhaler, family = cumulative(),
prior = set_prior("normal(0,5)"))
summary(fit2)
plot(fit2)
## End(Not run)
InvGaussian The Inverse Gaussian Distribution
#### Description 
Density, distribution function, and random generation for the inverse Gaussian distribution with
location mu, and shape shape.
Usage
dinv_gaussian(x, mu = 1, shape = 1, log = FALSE)
pinv_gaussian(q, mu = 1, shape = 1, lower.tail = TRUE,
log.p = FALSE)
rinv_gaussian(n, mu = 1, shape = 1)
#### Arguments
x, q Vector of quantiles.
mu Vector of locations.
shape Vector of shapes.
log Logical; If TRUE, #### Values are returned on the log scale.
76 is.brmsfit
lower.tail Logical; If TRUE (default), return P(X <= x). Else, return P(X > x) .
log.p Logical; If TRUE, #### Values are returned on the log scale.
n Number of samples to draw from the distribution.
#### Details
See vignette("brms_families") for #### Details on the parameterization.
inv_logit_scaled Scaled inverse logit-link
#### Description 
Computes inv_logit(x) * (ub - lb) + lb
Usage
inv_logit_scaled(x, lb = 0, ub = 1)
#### Arguments
x A numeric or complex vector.
lb Lower bound defaulting to 0.
ub Upper bound defaulting to 1.
#### Value
A numeric or complex vector between lb and ub.
is.brmsfit Checks if argument is a brmsfit object
#### Description 
Checks if argument is a brmsfit object
Usage
is.brmsfit(x)
#### Arguments
x An R object
is.brmsfit_multiple 77
is.brmsfit_multiple Checks if argument is a brmsfit_multiple object
#### Description 
Checks if argument is a brmsfit_multiple object
Usage
is.brmsfit_multiple(x)
#### Arguments
x An R object
is.brmsformula Checks if argument is a brmsformula object
#### Description 
Checks if argument is a brmsformula object
Usage
is.brmsformula(x)
#### Arguments
x An R object
is.brmsprior Checks if argument is a brmsprior object
#### Description 
Checks if argument is a brmsprior object
Usage
is.brmsprior(x)
#### Arguments
x An R object
78 is.cor_brms
is.brmsterms Checks if argument is a brmsterms object
#### Description 
Checks if argument is a brmsterms object
Usage
is.brmsterms(x)
#### Arguments
x An R object
See Also
parse_bf
is.cor_brms Check if argument is a correlation structure
#### Description 
Check if argument is one of the correlation structures used in brms.
Usage
is.cor_brms(x)
is.cor_arma(x)
is.cor_sar(x)
is.cor_car(x)
is.cor_fixed(x)
is.cor_bsts(x)
#### Arguments
x An R object.
is.mvbrmsformula 79
is.mvbrmsformula Checks if argument is a mvbrmsformula object
#### Description 
Checks if argument is a mvbrmsformula object
Usage
is.mvbrmsformula(x)
#### Arguments
x An R object
is.mvbrmsterms Checks if argument is a mvbrmsterms object
#### Description 
Checks if argument is a mvbrmsterms object
Usage
is.mvbrmsterms(x)
#### Arguments
x An R object
See Also
parse_bf
80 kfold.brmsfit
kfold.brmsfit K-Fold Cross-Validation
#### Description 
Perform exact K-fold cross-validation by refitting the model K times each leaving out one-Kth of
the original data.
Usage
## S3 method for class 'brmsfit'
kfold(x, ..., compare = TRUE, K = 10, Ksub = NULL,
folds = NULL, group = NULL, exact_loo = NULL, resp = NULL,
model_names = NULL, save_fits = FALSE)
kfold(x, ...)
#### Arguments
x A fitted model object.
... More fitted model objects or further #### Arguments passed to the underlying postprocessing
functions.
compare A flag indicating if the information criteria of the models should be compared
to each other via compare_ic.
K The number of subsets of equal (if possible) size into which the data will be
partitioned for performing K-fold cross-validation. The model is refit K times,
each time leaving out one of the K subsets. If K is equal to the total number
of observations in the data then K-fold cross-validation is equivalent to exact
leave-one-out cross-validation.
Ksub Optional number of subsets (of those subsets defined by K) to be evaluated. If
NULL (the default), K-fold cross-validation will be performed on all subsets.
If Ksub is a single integer, Ksub subsets (out of all K) subsets will be randomly
chosen. If Ksub consists of multiple integers or a one-dimensional array (created
via as.array) potentially of length one, the corresponding subsets will be used.
This argument is primarily useful, if evaluation of all subsets is infeasible for
some reason.
folds Determines how the subsets are being constructed. Possible #### Values are NULL
(the default), "stratified", "balanced", or "loo". May also be a vector of
length equal to the number of observations in the data. Alters the way group is
handled. More information is provided in the ’#### Details’ section.
group Optional name of a grouping variable or factor in the model. What exactly
is done with this variable depends on argument folds. More information is
provided in the ’#### Details’ section.
exact_loo Deprecated! Please use folds = "loo" instead.
kfold.brmsfit 81
* `` resp``: Optional names of response variables. If specified, predictions are performed
only for the specified response variables.
model_names If NULL (the default) will use model names derived from deparsing the call. Otherwise
will use the passed #### Values as model names.
save_fits If TRUE, a component fits is added to the returned object to store the crossvalidated
brmsfit objects and the indices of the omitted observations for each
fold. Defaults to FALSE.
#### Details
The kfold function performs exact K-fold cross-validation. First the data are partitioned into K
folds (i.e. subsets) of equal (or as close to equal as possible) size by default. Then the model is refit
K times, each time leaving out one of the K subsets. IfK is equal to the total number of observations
in the data then K-fold cross-validation is equivalent to exact leave-one-out cross-validation (to
which loo is an efficient approximation). The compare_ic function is also compatible with the
objects returned by kfold.
The subsets can be constructed in multiple different ways:
• If both folds and group are NULL, the subsets are randomly chosen so that they have equal
(or as close to equal as possible) size.
• If folds is NULL but group is specified, the data is split up into subsets, each time omitting all
observations of one of the factor levels, while ignoring argument K.
• If folds = "stratified" the subsets are stratified after group using loo::kfold_split_stratified.
• If folds = "balanced" the subsets are balanced by group using loo::kfold_split_balanced.
• If folds = "loo" exact leave-one-out cross-validation will be performed and K will be ignored.
Further, if group is specified, all observations corresponding to the factor level of the
currently predicted single #### Value are omitted. Thus, in this case, the predicted #### Values are only
a subset of the omitted ones.
• If folds is a numeric vector, it must contain one element per observation in the data. Each
element of the vector is an integer in 1:K indicating to which of the K folds the corresponding
observation belongs. There are some convenience functions available in the loo package that
create integer vectors to use for this purpose (see the Examples section below and also the
kfold-helpers page).
#### Value
kfold returns an object that has a similar structure as the objects returned by the loo and waic
methods.
See Also
loo, reloo
82 kidney
Examples
## Not run:
fit1 <- brm(count ~ log_Age_c + log_Base4_c * Trt +
(1|patient) + (1|obs),
data = epilepsy, family = poisson())
# throws warning about some pareto k estimates being too high
(loo1 <- loo(fit1))
# perform 10-fold cross validation
(kfold1 <- kfold(fit1, chains = 1)
## End(Not run)
kidney Infections in kidney patients
#### Description 
This dataset, originally discussed in McGilchrist and Aisbett (1991), describes the first and second
(possibly right censored) recurrence time of infection in kidney patients using portable dialysis
equipment. In addition, information on the risk variables age, sex and disease type is provided.
Usage
kidney
Format
A dataframe of 76 observations containing information on the following 7 variables.
time The time to first or second recurrence of the infection, or the time of censoring
recur A factor of levels 1 or 2 indicating if the infection recurred for the first or second time for
this patient
censored Either 0 or 1, where 0 indicates no censoring of recurrence time and 1 indicates right
censoring
patient The patient number
age The age of the patient
sex The sex of the patient
disease A factor of levels other, GN, AN, and PKD specifying the type of disease
Source
McGilchrist, C. A., & Aisbett, C. W. (1991). Regression with frailty in survival analysis. Biometrics,
47(2), 461-466.
lasso 83
Examples
## Not run:
## performing surivival analysis using the "weibull" family
fit1 <- brm(time | cens(censored) ~ age + sex + disease,
data = kidney, family = weibull, inits = "0")
summary(fit1)
plot(fit1)
## adding random intercepts over patients
fit2 <- brm(time | cens(censored) ~ age + sex + disease + (1|patient),
data = kidney, family = weibull(), inits = "0",
prior = set_prior("cauchy(0,2)", class = "sd"))
summary(fit2)
plot(fit2)
## End(Not run)
lasso Set up a lasso prior in brms
#### Description 
Function used to set up a lasso prior for population-level effects in brms. The function does not
evaluate its #### Arguments – it exists purely to help set up the model.
Usage
lasso(df = 1, scale = 1)
#### Arguments
df Degrees of freedom of the chi-square prior of the inverse tuning parameter. Defaults
to 1.
scale Scale of the lasso prior. Defaults to 1.
#### Details
The lasso prior is the Bayesian equivalent to the LASSO method for performing variable selection
(Park & Casella, 2008). With this prior, independent Laplace (i.e. double exponential) priors are
placed on the population-level effects. The scale of the Laplace priors depends on a tuning parameter
that controls the amount of shrinkage. In brms, the inverse of the tuning parameter is used
so that smaller #### Values imply more shrinkage. The inverse tuning parameter has a chi-square distribution
and with degrees of freedom controlled via argument df of function lasso (defaults to
1). For instance, one can specify a lasso prior using set_prior("lasso(1)"). To make sure that
shrinkage can equally affect all coefficients, predictors should be one the same scale. If you do not
want to standardized all variables, you can adjust the general scale of the lasso prior via argument
scale, for instance, lasso(1, scale = 10).
84 launch_shinystan.brmsfit
#### Value
A character string obtained by match.call() with additional #### Arguments.
References
Park, T., & Casella, G. (2008). The Bayesian Lasso. Journal of the American Statistical Association,
103(482), 681-686.
See Also
set_prior
Examples
set_prior(lasso(df = 1, scale = 10))
launch_shinystan.brmsfit
Interface to shinystan
#### Description 
Provide an interface to shinystan for models fitted with brms
Usage
## S3 method for class 'brmsfit'
launch_shinystan(object,
rstudio = getOption("shinystan.rstudio"), ...)
#### Arguments
object A fitted model object typically of class brmsfit.
rstudio Only relevant for RStudio users. The default (rstudio=FALSE) is to launch the
app in the default web browser rather than RStudio’s pop-up Viewer. Users can
change the default to TRUE by setting the global option
options(shinystan.rstudio = TRUE).
... Optional #### Arguments to pass to runApp
#### Value
An S4 shinystan object
See Also
launch_shinystan
logit_scaled 85
Examples
## Not run:
fit <- brm(rating ~ treat + period + carry + (1|subject),
data = inhaler, family = "gaussian")
launch_shinystan(fit)
## End(Not run)
logit_scaled Scaled logit-link
#### Description 
Computes logit((x - lb) / (ub - lb))
Usage
logit_scaled(x, lb = 0, ub = 1)
#### Arguments
x A numeric or complex vector.
lb Lower bound defaulting to 0.
ub Upper bound defaulting to 1.
#### Value
A numeric or complex vector.
logm1 Logarithm with a minus one offset.
#### Description 
Computes log(x - 1).
Usage
logm1(x, base = exp(1))
#### Arguments
x A numeric or complex vector.
base A positive or complex number: the base with respect to which logarithms are
computed. Defaults to e = exp(1).
86 log_lik.brmsfit
log_lik.brmsfit Compute the Pointwise Log-Likelihood
#### Description 
Compute the Pointwise Log-Likelihood
Usage
## S3 method for class 'brmsfit'
log_lik(object, newdata = NULL, re_formula = NULL,
resp = NULL, nsamples = NULL, subset = NULL, pointwise = FALSE,
combine = TRUE, ...)
#### Arguments
object A fitted model object of class brmsfit.
newdata An optional data.frame for which to evaluate predictions. If NULL (default), the
original data of the model is used.
re_formula formula containing group-level effects to be considered in the prediction. If
NULL (default), include all group-level effects; if NA, include no group-level effects.
* `` resp``: Optional names of response variables. If specified, predictions are performed
only for the specified response variables.
nsamples Positive integer indicating how many posterior samples should be used. If NULL
(the default) all samples are used. Ignored if subset is not NULL.
subset A numeric vector specifying the posterior samples to be used. If NULL (the
default), all samples are used.
pointwise A flag indicating whether to compute the full log-likelihood matrix at once (the
default), or just return the likelihood function along with all data and samples
required to compute the log-likelihood separately for each observation. The
latter option is rarely useful when calling log_lik directly, but rather when
computing waic or loo.
* ``combine ``:  Only relevant in multivariate models. Indicates if the log-likelihoods of the submodels
should be combined per observation (i.e. added together; the default) or
if the log-likelihoods should be returned separately.
* `` ... ``: Further arguments passed to extract_draws that control several aspects of data
validation and prediction.
#### Value
Usually, an S x N matrix containing the pointwise log-likelihood samples, where S is the number
of samples and N is the number of observations in the data. For multivariate models and if
combine is FALSE, an S x N x R array is returned, where R is the number of response variables. If
pointwise = TRUE, the output is a function with a draws attribute containing all relevant data and
posterior samples.
log_posterior.brmsfit 87
log_posterior.brmsfit Extract Diagnostic Quantities of brms Models
#### Description 
Extract quantities that can be used to diagnose sampling behavior of the algorithms applied by Stan
at the back-end of brms.
Usage
## S3 method for class 'brmsfit'
log_posterior(object, ...)
## S3 method for class 'brmsfit'
nuts_params(object, pars = NULL, ...)
## S3 method for class 'brmsfit'
rhat(object, pars = NULL, ...)
## S3 method for class 'brmsfit'
neff_ratio(object, pars = NULL, ...)
#### Arguments
object A brmsfit object.
... #### Arguments passed to individual methods.
pars An optional character vector of parameter names. For nuts_params these will
be NUTS sampler parameter names rather than model parameters. If pars is
omitted all parameters are included.
#### Details
for more details see bayesplot-extractors.
#### Value
The exact form of the output depends on the method.
Examples
## Not run:
fit <- brm(time ~ age * sex, data = kidney)
lp <- log_posterior(fit)
head(lp)
np <- nuts_params(fit)
str(np)
88 loo.brmsfit
# extract the number of divergence transitions
sum(subset(np, Parameter == "divergent__")$#### Value)
head(rhat(fit))
head(neff_ratio(fit))
## End(Not run)
