control_params.brmsfit
Extract Control Parameters of the NUTS Sampler
#### Description 
Extract control parameters of the NUTS sampler such as adapt_delta or max_treedepth.
cor_ar 43
Usage
## S3 method for class 'brmsfit'
control_params(x, pars = NULL, ...)
control_params(x, ...)
#### Arguments
x An R object
pars Optional names of the control parameters to be returned. If NULL (the default)
all control parameters are returned. See stan for more details.
... Currently ignored.
#### Value
A named list with control parameter #### Values.
cor_ar AR(p) correlation structure
#### Description 
This function is a constructor for the cor_arma class, allowing for autoregression terms only.
Usage
cor_ar(formula = ~1, p = 1, cov = FALSE)
#### Arguments
formula A one sided formula of the form ~ t, or ~ t | g, specifying a time covariate
t and, optionally, a grouping factor g. A covariate for this correlation structure
must be integer #### Valued. When a grouping factor is present in formula, the
correlation structure is assumed to apply only to observations within the same
grouping level; observations with different grouping levels are assumed to be
uncorrelated. Defaults to ~ 1, which corresponds to using the order of the
observations in the data as a covariate, and no groups.
p A non-negative integer specifying the autoregressive (AR) order of the ARMA
structure. Default is 1.
cov A flag indicating whether ARMA effects should be estimated by means of residual
covariance matrices (currently only possible for stationary ARMA effects of
order 1). If FALSE (the default) a regression formulation is used that is considerably
faster and allows for ARMA effects of order higher than 1 but cannot
handle user defined standard errors.
44 cor_arma
#### Details
AR refers to autoregressive effects of residuals, which is what is typically understood as autoregressive
effects. However, one may also model autoregressive effects of the response variable, which is
called ARR in brms.
#### Value
An object of class cor_arma containing solely autoregression terms.
Author(s)
Paul-Christian Buerkner <paul.buerkner@gmail.com>
See Also
cor_arma
Examples
cor_ar(~visit|patient, p = 2)
cor_arma ARMA(p,q) correlation structure
#### Description 
This functions is a constructor for the cor_arma class, representing an autoregression-moving average
correlation structure of order (p, q).
Usage
cor_arma(formula = ~1, p = 0, q = 0, r = 0, cov = FALSE)
#### Arguments
formula A one sided formula of the form ~ t, or ~ t | g, specifying a time covariate
t and, optionally, a grouping factor g. A covariate for this correlation structure
must be integer #### Valued. When a grouping factor is present in formula, the
correlation structure is assumed to apply only to observations within the same
grouping level; observations with different grouping levels are assumed to be
uncorrelated. Defaults to ~ 1, which corresponds to using the order of the
observations in the data as a covariate, and no groups.
p A non-negative integer specifying the autoregressive (AR) order of the ARMA
structure. Default is 0.
q A non-negative integer specifying the moving average (MA) order of the ARMA
structure. Default is 0.
cor_arr 45
r A non-negative integer specifying the autoregressive response (ARR) order. See
’#### Details’ for differences of AR and ARR effects. Default is 0.
cov A flag indicating whether ARMA effects should be estimated by means of residual
covariance matrices (currently only possible for stationary ARMA effects of
order 1). If FALSE (the default) a regression formulation is used that is considerably
faster and allows for ARMA effects of order higher than 1 but cannot
handle user defined standard errors.
#### Details
AR refers to autoregressive effects of residuals, which is what is typically understood as autoregressive
effects. However, one may also model autoregressive effects of the response variable, which is
called ARR in brms.
#### Value
An object of class cor_arma, representing an autoregression-moving-average correlation structure.
Author(s)
Paul-Christian Buerkner <paul.buerkner@gmail.com>
See Also
cor_ar, cor_ma, cor_arr
Examples
cor_arma(~visit|patient, p = 2, q = 2)
cor_arr ARR(r) correlation structure
#### Description 
This function is a constructor for the cor_arma class allowing for autoregressive effects of the
response only.
Usage
cor_arr(formula = ~1, r = 1)
46 cor_brms
#### Arguments
formula A one sided formula of the form ~ t, or ~ t | g, specifying a time covariate
t and, optionally, a grouping factor g. A covariate for this correlation structure
must be integer #### Valued. When a grouping factor is present in formula, the
correlation structure is assumed to apply only to observations within the same
grouping level; observations with different grouping levels are assumed to be
uncorrelated. Defaults to ~ 1, which corresponds to using the order of the
observations in the data as a covariate, and no groups.
r A non-negative integer specifying the autoregressive response (ARR) order of
the ARMA structure. Default is 1.
#### Details
AR refers to autoregressive effects of residuals, which is what is typically understood as autoregressive
effects. However, one may also model autoregressive effects of the response variable, which is
called ARR in brms.
#### Value
An object of class cor_arma containing solely autoregressive response terms.
Author(s)
Paul-Christian Buerkner <paul.buerkner@gmail.com>
See Also
cor_arma
Examples
cor_arr(~visit|patient, r = 2)
cor_brms Correlation structure classes for the brms package
#### Description 
Classes of correlation structures available in the brms package. cor_brms is not a correlation
structure itself, but the class common to all correlation structures implemented in brms.
cor_bsts 47
Available correlation structures
cor_arma autoregressive-moving average (ARMA) structure, with arbitrary orders for the autoregressive
and moving average components
cor_ar autoregressive (AR) structure of arbitrary order
cor_ma moving average (MA) structure of arbitrary order
cor_arr response autoregressive (ARR) structure
cor_car Spatial conditional autoregressive (CAR) structure
cor_sar Spatial simultaneous autoregressive (SAR) structure
cor_bsts Bayesian structural time series (BSTS) structure
cor_fixed fixed user-defined covariance structure
See Also
cor_arma, cor_ar, cor_ma, cor_arr, cor_car, cor_sar, cor_bsts, cor_fixed
cor_bsts Basic Bayesian Structural Time Series
#### Description 
Add a basic Bayesian structural time series component to a brms model
Usage
cor_bsts(formula = ~1)
#### Arguments
formula A one sided formula of the form ~ t, or ~ t | g, specifying a time covariate
t and, optionally, a grouping factor g. A covariate for this correlation structure
must be integer #### Valued. When a grouping factor is present in formula, the
correlation structure is assumed to apply only to observations within the same
grouping level; observations with different grouping levels are assumed to be
uncorrelated. Defaults to ~ 1, which corresponds to using the order of the
observations in the data as a covariate, and no groups.
#### Details
Bayesian structural time series models offer an alternative to classical AR(I)MA models (they are
in fact a generalization). The basic version currently implemented in brms introduces local level
terms for each observation, whereas each local level term depends on the former local level term:
LLt N(LLt􀀀1; sigmaLL)
A simple introduction can be found in this blogpost: http://multithreaded.stitchfix.com/
blog/2016/04/21/forget-arima/. More complicated Bayesian structural time series models
may follow in the future.
48 cor_car
#### Value
An object of class cor_bsts.
Examples
## Not run:
dat <- data.frame(y = rnorm(100), x = rnorm(100))
fit <- brm(y~x, data = dat, autocor = cor_bsts())
## End(Not run)
cor_car Spatial conditional autoregressive (CAR) structures
#### Description 
These functions are constructors for the cor_car class implementing spatial conditional autoregressive
structures.
Usage
cor_car(W, formula = ~1, type = c("escar", "esicar", "icar"))
cor_icar(W, formula = ~1)
#### Arguments
W Adjacency matrix of locations. All non-zero entries are treated as if the two
locations are adjacent. If formula contains a grouping factor, the row names of
W have to match the levels of the grouping factor.
formula An optional one-sided formula of the form ~ 1 | g, where g is a grouping factor
mapping observations to spatial locations. If not specified, each observation is
treated as a separate location. It is recommended to always specify a grouping
factor to allow for handling of new data in post-processing methods.
type Type of the CAR structure. Currently implemented are "escar" (exact sparse
CAR) and "esicar" (exact sparse intrinsic CAR) and "icar" (intrinsic CAR).
More information is provided in the ’#### Details’ section.
#### Details
The escar and esicar types are implemented based on the case study of Max Joseph (https:
//github.com/mbjoseph/CARstan). The icar type is implemented based on the case study of
Mitzi Morris (http://mc-stan.org/users/documentation/case-studies/icar_stan.html).
cor_fixed 49
Examples
## Not run:
# generate some spatial data
east <- north <- 1:10
Grid <- expand.grid(east, north)
K <- nrow(Grid)
# set up distance and neighbourhood matrices
distance <- as.matrix(dist(Grid))
W <- array(0, c(K, K))
W[distance == 1] <- 1
# generate the covariates and response data
x1 <- rnorm(K)
x2 <- rnorm(K)
theta <- rnorm(K, sd = 0.05)
phi <- rmulti_normal(
1, mu = rep(0, K), Sigma = 0.4 * exp(-0.1 * distance)
)
eta <- x1 + x2 + phi
prob <- exp(eta) / (1 + exp(eta))
size <- rep(50, K)
y <- rbinom(n = K, size = size, prob = prob)
dat <- data.frame(y, size, x1, x2)
# fit a CAR model
fit <- brm(y | trials(size) ~ x1 + x2, data = dat,
family = binomial(), autocor = cor_car(W))
summary(fit)
## End(Not run)
