epilepsy Epileptic seizure counts
#### Description 
Breslow and Clayton (1993) analyze data initially provided by Thall and Vail (1990) concerning
seizure counts in a randomized trial of anti-convulsant therapy in epilepsy. Covariates are treatment,
8-week baseline seizure counts, and age of the patients in years.
Usage
epilepsy
Format
A dataframe of 236 observations containing information on the following 9 variables.
Age The age of the patients in years
Base The seizure count at 8-weeks baseline
Trt Either 0 or 1 indicating if the patient received anti-convulsant therapy
log_Age_c The logarithm of Age centered around its mean
log_Base4_c The logarithm of Base divided by 4 (i.e. log(Base/4)) centered around its mean
Trt_c Trt centered around its mean
visit The session number from 1 (first visit) to 4 (last visit)
count The seizure count between two visits
patient The patient number
obs The observation number, i.e. a unique identifier for each observation
Source
Thall, P. F., & Vail, S. C. (1990). Some covariance models for longitudinal count data with overdispersion.
Biometrics, 46(2), 657-671.
Breslow, N. E., & Clayton, D. G. (1993). Approximate inference in generalized linear mixed models.
Journal of the American Statistical Association, 88(421), 9-25.
ExGaussian 57
Examples
## Not run:
## poisson regression without random effects.
fit1 <- brm(count ~ log_Age_c + log_Base4_c * Trt_c,
data = epilepsy, family = poisson())
summary(fit1)
plot(fit1)
## poisson regression with random intercepts of patients and visits
## as well as normal priors for fixed effects parameters.
fit2 <- brm(count ~ log_Age_c + log_Base4_c * Trt_c
+ (1|patient) + (1|visit),
data = epilepsy, family = poisson(),
prior = set_prior("normal(0,5)"))
summary(fit2)
plot(fit2)
## End(Not run)
ExGaussian The Exponentially Modified Gaussian Distribution
#### Description 
Density, distribution function, and random generation for the exponentially modified Gaussian distribution
with mean mu and standard deviation sigma of the gaussian component, as well as scale
beta of the exponential component.
Usage
dexgaussian(x, mu, sigma, beta, log = FALSE)
pexgaussian(q, mu, sigma, beta, lower.tail = TRUE, log.p = FALSE)
rexgaussian(n, mu, sigma, beta)
#### Arguments
x, q Vector of quantiles.
mu Vector of means of the combined distribution.
sigma Vector of standard deviations of the gaussian component.
beta Vector of scales of the exponential component.
log Logical; If TRUE, #### Values are returned on the log scale.
lower.tail Logical; If TRUE (default), return P(X <= x). Else, return P(X > x) .
log.p Logical; If TRUE, #### Values are returned on the log scale.
n Number of samples to draw from the distribution.
58 expp1
#### Details
See vignette("brms_families") for #### Details on the parameterization.
expose_functions.brmsfit
Expose user-defined Stan functions
#### Description 
Export user-defined Stan function and optionally vectorize them. for more details see expose_stan_functions.
Usage
## S3 method for class 'brmsfit'
expose_functions(x, vectorize = FALSE,
env = globalenv(), ...)
expose_functions(x, ...)
#### Arguments
x An R object
vectorize Logical; Indicates if the exposed functions should be vectorized via Vectorize.
Defaults to FALSE.
env Environment where the functions should be made available. Defaults to the
global environment.
* `` ... ``: Further arguments passed to expose_stan_functions.
expp1 Exponential function plus one.
#### Description 
Computes exp(x) + 1.
Usage
expp1(x)
#### Arguments
x A numeric or complex vector.
extract_draws.brmsfit 59
extract_draws.brmsfit Extract Data and Posterior Draws
#### Description 
This method helps in preparing brms models for certin post-processing tasks most notably various
forms of predictions. Unless you are a package developer, you will rarely need to call extract_draws
directly.
Usage
## S3 method for class 'brmsfit'
extract_draws(x, newdata = NULL, re_formula = NULL,
allow_new_levels = FALSE, sample_new_levels = "uncertainty",
incl_autocor = TRUE, resp = NULL, nsamples = NULL, subset = NULL,
nug = NULL, smooths_only = FALSE, offset = TRUE,
new_objects = list(), ...)
extract_draws(x, ...)
#### Arguments
x An R object typically of class 'brmsfit'.
newdata An optional data.frame for which to evaluate predictions. If NULL (default), the
original data of the model is used.
re_formula formula containing group-level effects to be considered in the prediction. If
NULL (default), include all group-level effects; if NA, include no group-level effects.
allow_new_levels
A flag indicating if new levels of group-level effects are allowed (defaults to
FALSE). Only relevant if newdata is provided.
sample_new_levels
Indicates how to sample new levels for grouping factors specified in re_formula.
This argument is only relevant if newdata is provided and allow_new_levels is
set to TRUE. If "uncertainty" (default), include group-level uncertainty in the
predictions based on the variation of the existing levels. If "gaussian", sample
new levels from the (multivariate) normal distribution implied by the group-level
standard deviations and correlations. This options may be useful for conducting
Bayesian power analysis. If "old_levels", directly sample new levels from the
existing levels.
incl_autocor A flag indicating if ARMA autocorrelation parameters should be included in the
predictions. Defaults to TRUE. Setting it to FALSE will not affect other correlation
structures such as cor_bsts, or cor_fixed.
* `` resp``: Optional names of response variables. If specified, predictions are performed
only for the specified response variables.
60 fitted.brmsfit
nsamples Positive integer indicating how many posterior samples should be used. If NULL
(the default) all samples are used. Ignored if subset is not NULL.
subset A numeric vector specifying the posterior samples to be used. If NULL (the
default), all samples are used.
nug Small positive number for Gaussian process terms only. For numerical reasons,
the covariance matrix of a Gaussian process might not be positive definite.
Adding a very small number to the matrix’s diagonal often solves this problem.
If NULL (the default), nug is chosen internally.
smooths_only Logical; If TRUE only draws related to the computation of smooth terms will be
extracted.
offset Logical; Indicates if offsets should be included in the predictions. Defaults to
TRUE.
new_objects A named list of objects containing new data, which cannot be passed via argument
newdata. Currently, only required for objects passed to cor_sar and
cor_fixed.
* `` ... ``: Further arguments passed to validate_newdata.
#### Value
An object of class 'brmsdraws' or 'mvbrmsdraws', depending on whether a univariate or multivariate
model is passed.
fitted.brmsfit Extract Model Fitted #### Values of brmsfit Objects
#### Description 
Predict mean #### Values of the response distribution (i.e., the ’regression line’) for a fitted model. Can
be performed for the data used to fit the model (posterior predictive checks) or for new data. By
definition, these predictions have smaller variance than the response predictions performed by the
predict method. This is because the measurement error is not incorporated. The estimated means
of both methods should, however, be very similar.
Usage
## S3 method for class 'brmsfit'
fitted(object, newdata = NULL, re_formula = NULL,
scale = c("response", "linear"), resp = NULL, dpar = NULL,
nlpar = NULL, nsamples = NULL, subset = NULL, sort = FALSE,
summary = TRUE, robust = FALSE, probs = c(0.025, 0.975), ...)
## S3 method for class 'brmsfit'
posterior_linpred(object, transform = FALSE,
newdata = NULL, re_formula = NULL, re.form = NULL, resp = NULL,
dpar = NULL, nlpar = NULL, nsamples = NULL, subset = NULL,
sort = FALSE, ...)
fitted.brmsfit 61
#### Arguments
object An object of class brmsfit.
newdata An optional data.frame for which to evaluate predictions. If NULL (default), the
original data of the model is used.
re_formula formula containing group-level effects to be considered in the prediction. If
NULL (default), include all group-level effects; if NA, include no group-level effects.
scale Either "response" or "linear". If "response" results are returned on the scale
of the response variable. If "linear" fitted #### Values are returned on the scale of
the linear predictor.
* `` resp``: Optional names of response variables. If specified, predictions are performed
only for the specified response variables.
dpar Optional name of a predicted distributional parameter. If specified, fitted #### Values
of this parameters are returned.
nlpar Optional name of a predicted non-linear parameter. If specified, fitted #### Values of
this parameters are returned.
nsamples Positive integer indicating how many posterior samples should be used. If NULL
(the default) all samples are used. Ignored if subset is not NULL.
subset A numeric vector specifying the posterior samples to be used. If NULL (the
default), all samples are used.
sort Logical. Only relevant for time series models. Indicating whether to return
predicted #### Values in the original order (FALSE; default) or in the order of the time
series (TRUE).
summary Should summary statistics (i.e. means, sds, and 95% intervals) be returned instead
of the raw #### Values? Default is TRUE.
robust If FALSE (the default) the mean is used as the measure of central tendency and
the standard deviation as the measure of variability. If TRUE, the median and the
median absolute deviation (MAD) are applied instead. Only used if summary is
TRUE.
probs The percentiles to be computed by the quantile function. Only used if summary
is TRUE.
* `` ... ``: Further arguments passed to extract_draws that control several aspects of data
validation and prediction.
transform Logical; alias of scale. If TRUE, scale is set to "response". If FALSE, scale is
set to "linear". Only implemented for compatibility with the posterior_linpred
generic.
re.form Alias of re_formula.
#### Details
NA #### Values within factors in newdata, are interpreted as if all dummy variables of this factor are zero.
This allows, for instance, to make predictions of the grand mean when using sum coding.
Method posterior_linpred.brmsfit is an alias of fitted.brmsfit with scale = "linear"
and summary = FALSE.
62 fixef.brmsfit
#### Value
Fitted #### Values extracted from object. The output depends on the family: If summary = TRUE it is a
N x E x C array for categorical and ordinal models and a N x E matrix else. If summary = FALSE
it is a S x N x C array for categorical and ordinal models and a S x N matrix else. N is the number
of observations, S is the number of samples, C is the number of categories, and E is equal to
length(probs) + 2. In multivariate models, the output is an array of 3 dimensions, where the
third dimension indicates the response variables.
Examples
## Not run:
## fit a model
fit <- brm(rating ~ treat + period + carry + (1|subject),
data = inhaler)
## extract fitted #### Values
fitted_#### Values <- fitted(fit)
head(fitted_#### Values)
## plot fitted means against actual response
dat <- as.data.frame(cbind(Y = standata(fit)$Y, fitted_#### Values))
ggplot(dat) + geom_point(aes(x = Estimate, y = Y))
## End(Not run)
