density_ratio Compute Density Ratios
#### Description 
Compute the ratio of two densities at given points based on samples of the corresponding distributions.
Usage
density_ratio(x, y = NULL, point = 0, n = 4096, ...)
#### Arguments
x Vector of samples from the first distribution, usually the posterior distribution of
the quantity of interest.
y Optional vector of samples from the second distribution, usually the prior distribution
of the quantity of interest. If NULL (the default), only the density of x will
be evaluated.
point Numeric #### Values at which to evaluate and compare the densities. Defaults to 0.
n Single numeric #### Value. Influences the accuracy of the density estimation. See
density for #### Details.
* `` ... ``: Further arguments passed to density.
#### Details
In order to achieve sufficient accuracy in the density estimation, more samples than usual are required.
That is you may need an effective sample size of 10,000 or more to reliably estimate the
densities.
56 epilepsy
#### Value
A vector of length equal to length(point). If y is provided, the density ratio of x against y is
returned. Else, only the density of x is returned.
Examples
x <- rnorm(10000)
y <- rnorm(10000, mean = 1)
density_ratio(x, y, point = c(0, 1))
