



is.mvbrmsformula Checks if argument is a mvbrmsformula object
#### Description 
Checks if argument is a mvbrmsformula object

#### Usage
<pre><code>
is.mvbrmsformula(x)
</code></pre>
#### Arguments
x An R object


is.mvbrmsterms Checks if argument is a mvbrmsterms object
#### Description 
Checks if argument is a mvbrmsterms object

#### Usage
is.mvbrmsterms(x)
#### Arguments
* x An R object
See Also
parse_bf
80 kfold.brmsfit

## ``is.brmsfit_multiple`` Checks if argument is a brmsfit_multiple object
#### Description 
Checks if argument is a brmsfit_multiple object

### Usage
<pre><code>
is.brmsfit_multiple(x)
</code></pre>
#### Arguments
* x An R object

## ``is.brmsformula`` Checks if argument is a brmsformula object

#### Description 
Checks if argument is a brmsformula object

#### Usage
<pre><code>
is.brmsformula(x)
</code></pre>

#### Arguments
* x An R object

## ``is.brmsprior`` Checks if argument is a brmsprior object
#### Description 
Checks if argument is a brmsprior object
Usage
is.brmsprior(x)
#### Arguments
x An R object

is.brmsterms Checks if argument is a brmsterms object
#### Description 
Checks if argument is a brmsterms object

#### Usage
<pre><code>
is.brmsterms(x)
</code></pre>

#### Arguments
x An R object

See Also
parse_bf

## is.cor_brms Check if argument is a correlation structure
#### Description 
Check if argument is one of the correlation structures used in brms.

#### Usage

<pre><code>
is.cor_brms(x)
is.cor_arma(x)
is.cor_sar(x)
is.cor_car(x)
is.cor_fixed(x)
is.cor_bsts(x)
</code></pre>

#### Arguments
x An R object.
