ExGaussian The Exponentially Modified Gaussian Distribution
#### Description 
Density, distribution function, and random generation for the exponentially modified Gaussian distribution
with mean mu and standard deviation sigma of the gaussian component, as well as scale
beta of the exponential component.

#### Usage
<pre><code>
dexgaussian(x, mu, sigma, beta, log = FALSE)
pexgaussian(q, mu, sigma, beta, lower.tail = TRUE, log.p = FALSE)
rexgaussian(n, mu, sigma, beta)
</code></pre>

#### Arguments
x, q Vector of quantiles.
* mu Vector of means of the combined distribution.
* sigma Vector of standard deviations of the gaussian component.
* beta Vector of scales of the exponential component.
* log Logical; If TRUE, #### Values are returned on the log scale.
* lower.tail Logical; If TRUE (default), return P(X <= x). Else, return P(X > x) .
* log.p Logical; If TRUE, #### Values are returned on the log scale.
* n Number of samples to draw from the distribution.

#### Details
See vignette("brms_families") for #### Details on the parameterization.
