
ZeroInflated 165
ZeroInflated Zero-Inflated Distributions
#### Description 
Density and distribution functions for zero-inflated distributions.

#### Usage
<pre><code>
dzero_inflated_poisson(x, lambda, zi, log = FALSE)
pzero_inflated_poisson(q, lambda, zi, lower.tail = TRUE, log.p = FALSE)
dzero_inflated_negbinomial(x, mu, shape, zi, log = FALSE)
pzero_inflated_negbinomial(q, mu, shape, zi, lower.tail = TRUE,
log.p = FALSE)
dzero_inflated_binomial(x, size, prob, zi, log = FALSE)
pzero_inflated_binomial(q, size, prob, zi, lower.tail = TRUE,
log.p = FALSE)
dzero_inflated_beta(x, shape1, shape2, zi, log = FALSE)
pzero_inflated_beta(q, shape1, shape2, zi, lower.tail = TRUE,
log.p = FALSE)
</code></pre>
#### Arguments

x Vector of quantiles.
zi zero-inflation propability
log Logical; If TRUE,values are returned on the log scale.
q Vector of quantiles.
lower.tail Logical; If TRUE (default), return P(X <= x). Else, return P(X > x) .
log.p Logical; If TRUE,values are returned on the log scale.
mu, lambda location parameter
shape, shape1, shape2
shape parameter
size number of trials
prob probability of success on each trial
#### Details
The density of a zero-inflated distribution can be specified as follows. If x = 0 set f(x) = +(1􀀀
)  g(0). Else set f(x) = (1 􀀀 )  g(x), where g(x) is the density of the non-zero-inflated part.
